### PR TITLE
Feat setup authflow

### LINKED ISSUE #61: Set up Authentication flow
**Is your feature request related to a problem? Please describe.**
- Set up Google Authentication flow

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by brianwachira**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
This PR introduces Google Authentication.

Fixes #61 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by makunomark** [comment]
@brianwachira will these changes work on a standalone build?

**Comment by makunomark** [comment]
With #65 do we still need this?

**Comment by makunomark** [comment]
> With #65 do we still need this?

@brianwachira

**Comment by brianwachira** [comment]
> With #65 do we still need this?

I am far away from my laptop but after that merge from #65 maybe not

**Pull request closed without merging**
