### PR TITLE
Feature homescreen

### LINKED ISSUE #10: [ui] : Create Home Screen ( Home not-loggedin and Home loggedin)
- Create Home Screen as per the guideline - [Home Design Adobe XD Link](https://xd.adobe.com/view/dd5d0245-b92b-4678-9d4a-48b3a6f48191-880e/screen/b09d2509-32d4-46ed-ab0c-e41444e175c3/specs/)
- Follow contribution guidelines laid out in our [contribution guide](https://github.com/droidconKE/droidconKE2022ReactNative/blob/develop/CONTRIBUTING.md)

**Additional context**
- Home not-logged-in
Screenshot 2022-09-12 at 23 05 03

- Home logged-in
Screenshot 2022-09-12 at 23 09 44

### PR DESCRIPTION
**Pull request by brianwachira**
# Description

Please include a summary of the change and which issue is fixed. Please also have relevant motivation and context. List any dependencies that are required for this change.
- Created `Home Not Logged In` & `Home Logged In` screens. This includes the modal that displays the log-in modal. 
- This feature adds [expo-av](https://docs.expo.dev/versions/latest/sdk/video/) package that loads videos on an Expo app.

- `Home Not Logged In`
photo_2022-10-01_15-03-13

- `Log In Modal`
photo_2022-10-01_15-03-26

- `Home Logged In`
photo_2022-10-01_15-03-34

Fixes #10

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by orama254 — APPROVED** [review]
LGTM!✅

also might you by any chance be participating in Hacktoberfest this year?

I can add an acceptance label so that it's added to your progress.

**Comment by brianwachira** [comment]
> LGTM!white_check_mark
> 
> also might you by any chance be participating in Hacktoberfest this year?
> 
> I can add an acceptance label so that it's added to your progress.

I am not but now that you mentioned it, why not?
Will this repository need a `Hactoberfest` label added?

**Comment by orama254** [comment]
> > LGTM!white_check_mark
> > also might you by any chance be participating in Hacktoberfest this year?
> > I can add an acceptance label so that it's added to your progress.
> 
> I am not but now that you mentioned it, why not? Will this repository need a `Hactoberfest` label added?

Not the repository, just this PR. I can assign 'hacktoberfest-accepted' on this PR and it will count towards your progress.

**Comment by brianwachira** [comment]
> > > LGTM!white_check_mark
> > > also might you by any chance be participating in Hacktoberfest this year?
> > > I can add an acceptance label so that it's added to your progress.
> > 
> > 
> > I am not but now that you mentioned it, why not? Will this repository need a `Hactoberfest` label added?
> 
> Not the repository, just this PR. I can assign 'hacktoberfest-accepted' on this PR and it will count towards your progress.

oh I see,
That is okay then :)

**Review by samdev254 — APPROVED** [review]

**Pull request merged**
